### PR TITLE
Added option for custom rules

### PR DESCRIPTION
**Pull request by harshithmohan**
Screenshot_20200501_203626

- Added a custom rule option which sends any download matching the pattern to the respective RPC URL instead of the default one.
- All links are sent to the default RPC if no rule is specified.
- Rules are checked top to bottom. So the topmost one takes most priority.

### CODE REVIEW

**Comment by alexhua** [comment]
Hi Harshith,

Appreciate your PR. It is a good idea to manage multi Aria2c RPC.
After careful review, I have some advice.
80815520-71244800-8beb-11ea-9e2b-28b9a169a41f
Whould you like you to revise the UI like above pic that is one RPC URL followed one URL pattern.

According to your code, only one URL will be selected by rule at the end, the top URL will be the default.  So I think this UI style is more simplicity and intuitive. And also if the users want to change the default URL,  they could just add " * " to that URL's rule. This feature could just meet the user's change default URL demand that had ever requested before.

Waiting for you response.
Thanks

**Comment by harshithmohan** [comment]
I hadn't thought of that. Thank you. This is how I made it now. Some people may have multiple patterns, so they can use them separated by a comma. Is this good?
Screenshot_20200509_210134

**Comment by alexhua** [comment]
Yes, it is what i mean.
I've added a new feature and some comments for you.
Would you please raise a new pull request based on the latest code? 
Thanks

**Comment by harshithmohan** [comment]
I've made the new PR, you can close this one

**Comment by alexhua** [comment]
raised a new one  #31

**Pull request closed without merging**
